sudu: required

services:
  - docker

before_install:
  - docker build -t hagaiglazner/docker-react -f Dockerfile.dev .

script: 
  - docker run hagaiglazner/docker-react npm run test -- --coverage

  
